//! Integration test: load the AES-256-GCM known-answer fixture and check the
//! paxe crate's own deterministic seal seams against it.
//!
//! The fixture (`tests/aes_gcm_vectors.json`) is generated by
//! `tests/gen_aes_gcm_vectors.py`, which computes the frames INDEPENDENTLY
//! using OpenSSL EVP via Python's `cryptography` package — it does not call
//! this crate. This test re-runs the crate's deterministic seams with the
//! same inputs and asserts byte-for-byte equality. If the crate's AAD
//! layout, field widths, or byte order drift, this test catches it even
//! though the crate's own unit tests would still pass (a self-consistent
//! crate round-trips its own frames).
//!
//! The fixture is embedded with `include_str!` so the test always runs
//! against the checked-in bytes, with no runtime file I/O. Regeneration is
//! documented in `tests/README.md`; the `kat` feature (see Cargo.toml)
//! exposes the deterministic seams this test needs.
//!
//! Run with:
//!   cargo test --test kat_from_json --features kat

#![cfg(feature = "kat")]

use paxe::dek;
use paxe::keystore::{Epoch, KeyStore};
use paxe::sodium::{self, KEYBYTES, NPUBBYTES};
use paxe::standard;

/// The checked-in fixture, embedded at compile time.
const JSON: &str = include_str!("aes_gcm_vectors.json");

/// Minimal, schema-specific extractor for the fixed JSON shape produced by
/// gen_aes_gcm_vectors.py. The crate has zero dependencies by policy, so we
/// do not pull a JSON crate; instead we find `"key": value` pairs by string
/// search. The schema is pinned by `schema: 1` and regenerated only by the
/// generator script, so this is robust for the one file shape it parses.
struct Json<'a> {
    s: &'a str,
}

impl<'a> Json<'a> {
    fn new(s: &'a str) -> Self {
        Self { s }
    }

    /// Return the raw text of the object bound to `key` (the brace-matched
    /// span). Used to descend into nested objects.
    fn object(&self, key: &str) -> Json<'_> {
        let start = self.key_index(key);
        let open = self.s[start..].find('{').expect("object `{`") + start;
        let mut depth = 0;
        let bytes = self.s.as_bytes();
        let mut i = open;
        while i < bytes.len() {
            match bytes[i] {
                b'{' => depth += 1,
                b'}' => {
                    depth -= 1;
                    if depth == 0 {
                        return Json::new(&self.s[open..=i]);
                    }
                }
                _ => {}
            }
            i += 1;
        }
        panic!("unterminated object for key `{key}`");
    }

    /// Return the string value of `key` (without quotes).
    fn string(&self, key: &str) -> &str {
        let start = self.key_index(key);
        let colon = self.s[start..].find(':').expect("colon") + start;
        let q0 = self.s[colon..].find('"').expect("open quote") + colon;
        let after = &self.s[q0 + 1..];
        let q1 = after.find('"').expect("close quote");
        &self.s[q0 + 1..q0 + 1 + q1]
    }

    /// Return the integer value of `key`.
    fn number(&self, key: &str) -> u64 {
        let start = self.key_index(key);
        let colon = self.s[start..].find(':').expect("colon") + start;
        let rest = self.s[colon + 1..].trim_start();
        let end = rest
            .find(|c: char| !c.is_ascii_digit())
            .unwrap_or(rest.len());
        rest[..end].parse::<u64>().expect("integer")
    }

    /// Return the array bound to `key` as a vec of each element's object span.
    fn array_objects(&self, key: &str) -> Vec<Json<'a>> {
        let start = self.key_index(key);
        let open = self.s[start..].find('[').expect("array `[`") + start;
        let mut out = Vec::new();
        let bytes = self.s.as_bytes();
        let mut i = open + 1;
        while i < bytes.len() {
            while i < bytes.len() && (bytes[i].is_ascii_whitespace() || bytes[i] == b',') {
                i += 1;
            }
            if i >= bytes.len() || bytes[i] == b']' {
                break;
            }
            if bytes[i] != b'{' {
                panic!("expected object in array for `{key}`");
            }
            let mut depth = 0;
            let begin = i;
            while i < bytes.len() {
                match bytes[i] {
                    b'{' => depth += 1,
                    b'}' => {
                        depth -= 1;
                        if depth == 0 {
                            out.push(Json::new(&self.s[begin..=i]));
                            i += 1;
                            break;
                        }
                    }
                    _ => {}
                }
                i += 1;
            }
        }
        out
    }

    fn key_index(&self, key: &str) -> usize {
        let needle = format!("\"{key}\"");
        self.s
            .find(&needle)
            .unwrap_or_else(|| panic!("missing key `{key}`"))
    }
}

fn unhex(s: &str) -> Vec<u8> {
    let b = s.as_bytes();
    assert!(b.len() % 2 == 0, "odd hex length");
    let mut out = Vec::with_capacity(b.len() / 2);
    let mut i = 0;
    while i < b.len() {
        let hi = (b[i] as char).to_digit(16).expect("hex");
        let lo = (b[i + 1] as char).to_digit(16).expect("hex");
        out.push(((hi << 4) | lo) as u8);
        i += 2;
    }
    out
}

/// Decode hex into a fixed-size array, panicking on a length mismatch.
fn unhex_arr<const N: usize>(s: &str) -> [u8; N] {
    let v = unhex(s);
    v.try_into().expect("hex length mismatch")
}

fn ep(v: u8) -> Epoch {
    Epoch::new(v).expect("epoch")
}

fn gcm_ready() -> bool {
    sodium::init().is_ok() && sodium::aes_gcm_available()
}

#[test]
fn standard_frame_matches_independent_fixture() {
    if !gcm_ready() {
        return;
    }
    let j = Json::new(JSON);
    let s = j.object("standard");

    let psk = unhex_arr::<KEYBYTES>(s.string("psk_hex"));
    let from_id = s.number("from_id") as u16;
    let to_id = s.number("to_id") as u16;
    let channel = s.number("channel") as u32;
    let epoch = s.number("epoch") as u8;
    let nonce = unhex_arr::<NPUBBYTES>(s.string("nonce_hex"));
    let plaintext = unhex(s.string("plaintext_hex"));
    let expected = unhex(s.string("frame_hex"));

    let mut store = KeyStore::new(from_id).expect("store");
    store.install(to_id, ep(epoch), &psk).expect("install psk");

    let frame =
        standard::seal_standard_deterministic(&store, to_id, channel, ep(epoch), &plaintext, nonce)
            .expect("seal standard");
    assert_eq!(
        frame, expected,
        "standard frame from crate does not match the independent fixture"
    );
}

#[test]
fn fanout_frames_match_independent_fixture() {
    if !gcm_ready() {
        return;
    }
    let j = Json::new(JSON);
    let f = j.object("fanout");

    let from_id = f.number("from_id") as u16;
    let channel = f.number("channel") as u32;
    let payload = unhex(f.string("payload_hex"));
    let dek = unhex_arr::<KEYBYTES>(f.string("dek_hex"));
    let body_nonce = unhex_arr::<NPUBBYTES>(f.string("body_nonce_hex"));

    let mut store = KeyStore::new(from_id).expect("store");
    let mut recipients_meta = Vec::new();
    for r in f.array_objects("recipients") {
        let to_id = r.number("to_id") as u16;
        let epoch = r.number("epoch") as u8;
        let psk = unhex_arr::<KEYBYTES>(r.string("psk_hex"));
        let env_nonce = unhex_arr::<NPUBBYTES>(r.string("envelope_nonce_hex"));
        let expected = unhex(r.string("frame_hex"));
        store.install(to_id, ep(epoch), &psk).expect("install");
        recipients_meta.push((to_id, epoch, env_nonce, expected));
    }

    let recipient_ids: Vec<u16> = recipients_meta.iter().map(|(t, _, _, _)| *t).collect();
    let env_nonces: Vec<[u8; NPUBBYTES]> = recipients_meta.iter().map(|(_, _, e, _)| *e).collect();

    let frames = dek::seal_fanout_deterministic(
        &store,
        &recipient_ids,
        channel,
        &payload,
        dek,
        body_nonce,
        &env_nonces,
    )
    .expect("seal fanout");

    assert_eq!(frames.len(), recipients_meta.len());
    for (frame, (_, _, _, expected)) in frames.iter().zip(&recipients_meta) {
        assert_eq!(
            frame.frame, *expected,
            "fanout frame from crate does not match the independent fixture"
        );
    }
    // Structural invariant: bodies (from offset 69) are identical across
    // recipients; prefixes differ.
    if frames.len() >= 2 {
        assert_eq!(frames[0].frame[69..], frames[1].frame[69..]);
        assert_ne!(frames[0].frame[..69], frames[1].frame[..69]);
    }
}
